name: Build release
on:
  push:
    tags:
      - '*'

jobs:
  Build-release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 'latest'

      - name: Install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
            pip install -r requirements.txt

      - name: Build application file
        run: |
          source .venv/bin/activate
          pyinstaller --onefile main.py

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
          draft: false
          prerelease: false

      - name: Build a zip file with the executable
        # The file is in the "dist" folder
        run: |
          zip -r release.zip dist

      - name: Upload new file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip